version: "3"
services:
  flask:
    image: flaskr
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      PYTHONUSERBASE: /usr/src/app/venv
    command: python flaskr.py
